# Generated by Django 3.2 on 2024-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20241119_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='order.Topping'),
        ),
    ]
