# Generated by Django 3.2 on 2024-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_1_5kg',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_1kg',
            field=models.DecimalField(decimal_places=2, default=2200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_2kg',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='product', to='order.Topping'),
        ),
    ]
